// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./resources/js/components/Admin/AdminHeader.vue')['default']
    AdminIndexCharts: typeof import('./resources/js/components/Admin/Index/AdminIndexCharts.vue')['default']
    AdminIndexStats: typeof import('./resources/js/components/Admin/Index/AdminIndexStats.vue')['default']
    AdminIndexTable: typeof import('./resources/js/components/Admin/Index/AdminIndexTable.vue')['default']
    AdminLayout: typeof import('./resources/js/layouts/AdminLayout.vue')['default']
    AdminMenusSlideOver: typeof import('./resources/js/components/Admin/Menus/AdminMenusSlideOver.vue')['default']
    AdminMenusTable: typeof import('./resources/js/components/Admin/Menus/AdminMenusTable.vue')['default']
    AdminNavigation: typeof import('./resources/js/components/Admin/AdminNavigation.vue')['default']
    AdminSideBar: typeof import('./resources/js/components/Admin/AdminSideBar.vue')['default']
    AppHeader: typeof import('./resources/js/components/App/AppHeader.vue')['default']
    AppIcon: typeof import('./resources/js/components/App/AppIcon.vue')['default']
    ApplicationLogo: typeof import('./resources/js/components/ApplicationLogo.vue')['default']
    AppLoginForm: typeof import('./resources/js/components/App/AppLoginForm.vue')['default']
    AppProfileMenu: typeof import('./resources/js/components/App/AppProfileMenu.vue')['default']
    AppProfileMenuItem: typeof import('./resources/js/components/App/AppProfileMenuItem.vue')['default']
    AppProfileMenuItems: typeof import('./resources/js/components/App/AppProfileMenuItems.vue')['default']
    AuthenticatedLayout: typeof import('./resources/js/layouts/AuthenticatedLayout.vue')['default']
    Checkbox: typeof import('./resources/js/components/Checkbox.vue')['default']
    ConfirmPassword: typeof import('./resources/js/Pages/Auth/ConfirmPassword.vue')['default']
    Dashboard: typeof import('./resources/js/Pages/Dashboard.vue')['default']
    Dropdown: typeof import('./resources/js/components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/components/DropdownLink.vue')['default']
    ForgotPassword: typeof import('./resources/js/Pages/Auth/ForgotPassword.vue')['default']
    GuestLayout: typeof import('./resources/js/layouts/GuestLayout.vue')['default']
    Icon: typeof import('./resources/js/components/Icon.vue')['default']
    InputError: typeof import('./resources/js/components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/components/InputLabel.vue')['default']
    JSlideOver: typeof import('./resources/js/components/J/JSlideOver.vue')['default']
    JTextArea: typeof import('./resources/js/components/J/JTextArea.vue')['default']
    JTextField: typeof import('./resources/js/components/J/JTextField.vue')['default']
    Login: typeof import('./resources/js/Pages/Auth/Login.vue')['default']
    NavLink: typeof import('./resources/js/components/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/components/PrimaryButton.vue')['default']
    Register: typeof import('./resources/js/Pages/Auth/Register.vue')['default']
    ResetPassword: typeof import('./resources/js/Pages/Auth/ResetPassword.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/components/ResponsiveNavLink.vue')['default']
    TextInput: typeof import('./resources/js/components/TextInput.vue')['default']
    VerifyEmail: typeof import('./resources/js/Pages/Auth/VerifyEmail.vue')['default']
    Welcome: typeof import('./resources/js/Pages/Welcome.vue')['default']
  }
}
