// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/Admin/AdminHeader.vue')['default']
    AdminIndexCharts: typeof import('./components/Admin/Index/AdminIndexCharts.vue')['default']
    AdminIndexStats: typeof import('./components/Admin/Index/AdminIndexStats.vue')['default']
    AdminIndexTable: typeof import('./components/Admin/Index/AdminIndexTable.vue')['default']
    AdminMenusSlideOver: typeof import('./components/Admin/Menus/AdminMenusSlideOver.vue')['default']
    AdminMenusTable: typeof import('./components/Admin/Menus/AdminMenusTable.vue')['default']
    AdminNavigation: typeof import('./components/Admin/AdminNavigation.vue')['default']
    AdminSideBar: typeof import('./components/Admin/AdminSideBar.vue')['default']
    AppHeader: typeof import('./components/App/AppHeader.vue')['default']
    AppIcon: typeof import('./components/App/AppIcon.vue')['default']
    ApplicationLogo: typeof import('./components/ApplicationLogo.vue')['default']
    AppLoginForm: typeof import('./components/App/AppLoginForm.vue')['default']
    AppProfileMenu: typeof import('./components/App/AppProfileMenu.vue')['default']
    AppProfileMenuItem: typeof import('./components/App/AppProfileMenuItem.vue')['default']
    AppProfileMenuItems: typeof import('./components/App/AppProfileMenuItems.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    DropdownLink: typeof import('./components/DropdownLink.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    InputError: typeof import('./components/InputError.vue')['default']
    InputLabel: typeof import('./components/InputLabel.vue')['default']
    JSlideOver: typeof import('./components/J/JSlideOver.vue')['default']
    JTextArea: typeof import('./components/J/JTextArea.vue')['default']
    JTextField: typeof import('./components/J/JTextField.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./components/ResponsiveNavLink.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
  }
}
