// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/Admin/AdminHeader.vue')['default']
    AdminIndexCharts: typeof import('./components/Admin/Index/AdminIndexCharts.vue')['default']
    AdminIndexStats: typeof import('./components/Admin/Index/AdminIndexStats.vue')['default']
    AdminIndexTable: typeof import('./components/Admin/Index/AdminIndexTable.vue')['default']
    AdminLayout: typeof import('./layouts/AdminLayout.vue')['default']
    AdminMenusSlideOver: typeof import('./components/Admin/Menus/AdminMenusSlideOver.vue')['default']
    AdminMenusTable: typeof import('./components/Admin/Menus/AdminMenusTable.vue')['default']
    AdminNavigation: typeof import('./components/Admin/AdminNavigation.vue')['default']
    AdminSideBar: typeof import('./components/Admin/AdminSideBar.vue')['default']
    AppHeader: typeof import('./components/App/AppHeader.vue')['default']
    AppIcon: typeof import('./components/App/AppIcon.vue')['default']
    ApplicationLogo: typeof import('./components/ApplicationLogo.vue')['default']
    AppLoginForm: typeof import('./components/App/AppLoginForm.vue')['default']
    AppProfileMenu: typeof import('./components/App/AppProfileMenu.vue')['default']
    AppProfileMenuItem: typeof import('./components/App/AppProfileMenuItem.vue')['default']
    AppProfileMenuItems: typeof import('./components/App/AppProfileMenuItems.vue')['default']
    AuthenticatedLayout: typeof import('./layouts/AuthenticatedLayout.vue')['default']
    Checkbox: typeof import('./components/Checkbox.vue')['default']
    Default: typeof import('./layouts/default.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    DropdownLink: typeof import('./components/DropdownLink.vue')['default']
    EmojioneV1Rocket: typeof import('~icons/emojione-v1/rocket')['default']
    GuestLayout: typeof import('./layouts/GuestLayout.vue')['default']
    HeroiconsBell: typeof import('~icons/heroicons/bell')['default']
    HeroiconsChevronDown20Solid: typeof import('~icons/heroicons/chevron-down20-solid')['default']
    HeroiconsMagnifyingGlass20Solid: typeof import('~icons/heroicons/magnifying-glass20-solid')['default']
    HeroiconsOutlineBars3CenterLeft: typeof import('~icons/heroicons-outline/bars3-center-left')['default']
    HeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    InputError: typeof import('./components/InputError.vue')['default']
    InputLabel: typeof import('./components/InputLabel.vue')['default']
    JButton: typeof import('./j-components/JButton.vue')['default']
    JCheckbox: typeof import('./j-components/JCheckbox.vue')['default']
    JLink: typeof import('./j-components/JLink.vue')['default']
    JSlideOver: typeof import('./j-components/JSlideOver.vue')['default']
    JTextArea: typeof import('./j-components/JTextArea.vue')['default']
    JTextField: typeof import('./j-components/JTextField.vue')['default']
    NavLink: typeof import('./components/NavLink.vue')['default']
    PrimaryButton: typeof import('./components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./components/ResponsiveNavLink.vue')['default']
    TextInput: typeof import('./components/TextInput.vue')['default']
  }
}
